use_frameworks!

platform :ios, '9.0'

target 'DWAlertController_Example' do
  pod 'DWAlertController', :path => '../'

  target 'DWAlertController_Tests' do
    inherit! :search_paths

    
  end
end
